Add nodejs websocket service
wso2/choreo-samples pull request #159
Opened 2024-10-16 10:54 UTC by Thushani-Jayasekera

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2024-10-16 10:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/choreo-samples?pullRequest=159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/choreo-samples?pullRequest=159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/choreo-samples?pullRequest=159) it.</sub>

2024-10-16 12:38 UTC, chameerar requested changes

2024-10-16 12:51 UTC, Thushani-Jayasekera commented on .samples/websocket-chat-app.yaml
> +buildPack: node
I checked with that as well previously. still the build failed.

2024-10-16 13:13 UTC, chameerar requested changes

2024-10-16 13:13 UTC, chameerar commented on .samples/websocket-chat-app.yaml
> +componentPath: /websocket-chat-app/websocket-chat-service-nodejs
Let's use `/websocket-chat-app` as the componentPath here.  Example - .samples/reading-list-app.yaml

Also let's add a readme to /websocket-chat-app to describe the contents of the subfolders. Example - reading-list-app/README.md

2024-10-16 13:15 UTC, chameerar commented on .samples/websocket-chat-app.yaml
> +buildPack: node
Looks like the issue is with the given componentPath. That can be fixed as described in https://github.com/wso2/choreo-samples/pull/159#discussion_r1803080655.

2024-10-17 06:29 UTC, chameerar approved these changes
LGTM

2024-10-17 07:04 UTC, merged